### ISSUE TITLE
Unable to start spark-master:0.9.0

### ISSUE THREAD

**Issue by jrabary** [amplab/docker-scripts#27]
Hi all,

I'm trying to deploy a spark cluster 0.9.0 but the script is blocked at the stage waiting for master.

The logs from the spark-master is as follow

SPARK_HOME=/opt/spark-0.9.0
HOSTNAME=master
SCALA_VERSION=2.10.3
PATH=/opt/spark-0.9.0:/opt/scala-2.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SPARK_VERSION=0.9.0
PWD=/
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
SHLVL=1
HOME=/
SCALA_HOME=/opt/scala-2.10.3
container=lxc
_=/usr/bin/env
MASTER_IP=172.17.0.6
preparing Spark
starting Hadoop Namenode
starting sshd
starting Spark Master

And `docker ps -a` shows :+1: 
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS               NAMES
8c19bdb67f2b        amplab/spark-master:0.9.0       /root/spark_master_f   4 minutes ago       Exit 1                                  boring_wright 

Is the Exit 1 correct ?

**Comment by AndreSchumacher** [comment]
Which Docker version are you using?

**Comment by jrabary** [comment]
I've tried with 0.7.6, 0.8.0 and 0.8.1

**Comment by ymote** [comment]
any update? Master docker could not start on Ubuntu 13.10, docker 8.0/8.1
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS               NAMES
8bec2574af1b        amplab/spark-master:0.9.0       /root/spark_master_f   17 minutes ago      Exit 1                                  backstabbing_mccarthy

**Comment by AndreSchumacher** [comment]
Could you try again? You need to repull the nameserver image, which should be quick. I just tested with Docker 0.8.1 on Ubuntu 13.10 and it works after the update.

**Comment by mnegbi** [comment]
Hi,

I'm having the same problem.
Tried with 0.8.1 on Ubuntu 13.10 after pulling the latest nameserver as suggested above.

**Comment by ghost** [comment]
Hello I am having also the same problem looping while waiting for master to start.

I am using vagrant with this image as a box 
https://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box

Installed docker as documented on the website http://docs.docker.io/en/latest/installation/ubuntulinux/

Installed also dnsmasq
__ /etc/default/dnsmasq__

```
ENABLED=1
CONFIG_DIR=/etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new
```

**/etc/resolv.conf**

```
nameserver 127.0.0.1
```

**/etc/hosts**

```
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
127.0.1.1 vagrant-ubuntu-saucy-64
```

and git clone your repository

I have tried with and without the user vagrant inside the docker group to avoid sudo

**docker version**

```
Client version: 0.8.1
Go version (client): go1.2
Git commit (client): a1598d1
Server version: 0.8.1
Git commit (server): a1598d1
Go version (server): go1.2
Last stable version: 0.8.1
```

__ uname -a__

```
Linux vagrant-ubuntu-saucy-64 3.11.0-17-generic #31-Ubuntu SMP Mon Feb 3 21:52:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**sudo ./deploy/deploy.sh -i amplab/spark:0.9.0 -w 3**

```
*** Starting Spark 0.9.0 ***
starting nameserver container
sudo docker run -d -h nameserver -v /tmp/dnsdir_24836:/etc/dnsmasq.d amplab/dnsmasq-precise
started nameserver container:  8f24c6b5339e631ce57c147529bf967b5f0bd282423b8ac765592087bc6c1d7f
DNS host->IP file mapped:      /tmp/dnsdir_24836/0hosts
NAMESERVER_IP:                 172.17.0.2
waiting for nameserver to come up
starting master container
sudo docker run -d -dns 172.17.0.2 -h master amplab/spark-master:0.9.0
started master container:      77ec7e2c070401ad83215966610e96f0712c8e2011330109bf7ddb1b12d8644a
MASTER_IP:                     172.17.0.3
waiting for master .............................................................................................................................................................................^Cvagrant@vagrant-ubuntu-saucy-64:~/spark/docker-scripts$
```

__ docker ps -a__

```
CONTAINER ID        IMAGE                           COMMAND                CREATED             STATUS              PORTS               NAMES
77ec7e2c0704        amplab/spark-master:0.9.0       /root/spark_master_f   4 minutes ago       Exit 255                                goofy_heisenberg
8f24c6b5339e        amplab/dnsmasq-precise:latest   /root/dnsmasq_files/   4 minutes ago       Up 4 minutes                            lonely_pare
```

**docker logs 8f24c6b5339e**

```
NAMESERVER_IP=172.17.0.2
```

**docker logs 77ec7e2c0704**

```
SPARK_HOME=/opt/spark-0.9.0
HOSTNAME=master
SCALA_VERSION=2.10.3
PATH=/opt/spark-0.9.0:/opt/scala-2.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SPARK_VERSION=0.9.0
PWD=/
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
SHLVL=1
HOME=/
SCALA_HOME=/opt/scala-2.10.3
container=lxc
_=/usr/bin/env
MASTER_IP=172.17.0.3
preparing Spark
starting Hadoop Namenode
starting sshd
starting Spark Master
```

**Vagrantfile**

```
VAGRANTFILE_API_VERSION = "2"

 Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "saucy"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-  cloudimg-amd64-vagrant-disk1.box"

    config.vm.provider "virtualbox" do |v|
       v.memory = 2048
    end
end
```

I have tried the configuration with ubuntu precise and encounter the same problem.

**Comment by AndreSchumacher** [comment]
Thanks for the detailed error report. Could you also post the output of `sudo docker logs 77ec7e2c070401ad8321596` (replace the last value with the ID of the master container)? Basically all the script does at that point is grep through the logs for some indication that the master has been started.

**Comment by hanebambel** [comment]
Hi Andre,

I'm experiencing the same problems as uburoifr mentions. As far as I see he already posted the output of the master container: docker logs 77ec7e2c0704

When starting the master container the last line of output I get to see is the following:
"starting Spark Master" 

The query-string "MasterWebUI: Started Master web UI" the script is waiting for does not appear :-(

Jan

**Comment by ghost** [comment]
Hello Andre,

Here are the logs for sudo docker logs 77ec7e2c070401ad8321596

```
SPARK_HOME=/opt/spark-0.9.0
HOSTNAME=master
SCALA_VERSION=2.10.3
PATH=/opt/spark-0.9.0:/opt/scala-2.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SPARK_VERSION=0.9.0
PWD=/
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
SHLVL=1
HOME=/
SCALA_HOME=/opt/scala-2.10.3
container=lxc
_=/usr/bin/env
MASTER_IP=172.17.0.3
preparing Spark
starting Hadoop Namenode
starting sshd
starting Spark Master
```

**Comment by AndreSchumacher** [comment]
Can you confirm that the image ID of spark-master in your local repository ("docker images") is 79d6b59ac67e? Sometimes there seem to be issues with re-pulling (partially) updated images. You may also want to "docker rmi" the Spark images and re-pull from scratch.

Otherwise you could ssh into the master and see what is going on. Maybe the firewall on your host is dropping the connection between workers and the master (just a guess). Instructions for ssh-ing into the master are in the Readme.

I will also still try Docker via vagrant on Mac OS to see if that works here. Otherwise I just tested Spark 0.9.0 on Docker 0.9.0 on Ubuntu 13.10 without problems.

**Comment by jrabary** [comment]
Still got an error. Here is what I have with the latest version of docker-script from github and docker 0.9.0 :

```
*** Starting Spark 0.9.0 ***
starting nameserver container
Unable to find image 'amplab/dnsmasq-precise' locally
Pulling repository amplab/dnsmasq-precise
d9cdba2ae123: Download complete 
511136ea3c5a: Download complete 
6170bb7b0ad1: Download complete 
9cd978db300e: Download complete 
8ba01b8ce182: Download complete 
f94adc58cf02: Download complete 
a1a1352f45a3: Download complete 
09520bb6755f: Download complete 
ba9c6da9abe1: Download complete 
4ac363a005d4: Download complete 
06c07389aeb1: Download complete 
479c22accaf4: Download complete 
e5168b11fe93: Download complete 
417b88aaf61a: Download complete 
started nameserver container:  40c0b03c7ae773f6c2d6bcca03a674e067db8ce9bd96e33853144b627be69a3f
DNS host->IP file mapped:      /tmp/dnsdir_11392/0hosts
NAMESERVER_IP:                 
waiting for nameserver to come up dig: couldn't get address for '': not found
.dig: couldn't get address for '': not found
.dig: couldn't get address for '': not found
.dig: couldn't get address for '': not found
.dig: couldn't get address for '': not found
```

**Comment by ghost** [comment]
Hi Andre,

I have tried to re-pull after using docker rmi. Did not work either still the same problem.
I have tried to connect with ssh to the master and I got a no route to host.

```
ssh: connect to host 172.17.0.4 port 22: No route to host
```

**Comment by dacaga** [comment]
Same problem here. I made some tests by getting into the spark master container manually and running the different scripts /root/spark_master_files/default_cmd runs.

It looks like there is a pam/permission problem:

```
service hadoop-namenode start
 * Starting Apache Hadoop Name Node server hadoop-namenode
start-stop-daemon: unable to start /usr/sbin/hadoop-daemon.sh (Permission denied)
```

```
sudo -u hdfs SPARK_VERSION=$SPARK_VERSION /run_spark_master.sh
```

Nothing happens.

And then, as root:

```
SPARK_VERSION=$SPARK_VERSION /run_spark_master.sh
[...]
14/03/26 06:09:49 INFO Master: Starting Spark master at spark://master:7077
14/03/26 06:09:49 INFO MasterWebUI: Started Master web UI at http://master:8080
14/03/26 06:09:49 INFO Master: I have been elected leader! New state: ALIVE
```

Trying to su as hdfs:

```
su hdfs -
su: User not known to the underlying authentication module
```

I've looked into it but i'm not sure what's causing that yet.

(Tested on Ubuntu 12.04 3.8.0-36-generic and a vagrant box 13.10 3.11.0-18-generic with docker 0.9.0)

**Comment by dacaga** [comment]
It worked after deleting the images and building them locally through docker-scripts/spark-0.9.0/build.

Is there something wrong with the images on the docker repository?

**Comment by clausd** [comment]
I've had very similar problems trying to run this on a Digital Ocean droplet under ubuntu 13.10/docker 0.8.0 - stopped waiting for master to boot - but the master container exited 

ae89d83f9cb5        amplab/spark-master:0.9.0          /root/spark_master_f   About an hour ago   Exit 1

**Comment by AndreSchumacher** [comment]
This is really weird. I deleted all containers and images locally on my native Ubuntu 13.10 and repulled the images from docker.io. They work fine here with Docker 0.9.0 and 0.9.1. But I confirm that on Mac OS when running the scripts inside the VM the master exists after 20 seconds or so. I will try rebuilding the images there and add more debug but I probably won't get to it by the end of next week. The Mac OS VM is running tinycore linux but why that would make a difference is unclear to me. @flowfeeler are you running native linux?
_update:_ I was thinking it could be the Virtualbox VM memory settings (default 1GB) but raising this didn't immediately help.

**Comment by dacaga** [comment]
it's currently working on a native ubuntu 12.04 Docker version 0.9.0

**Comment by michaelpisula** [comment]
I have the same problem on Ubuntu 13.10 and Docker 0.9.1. Removing the images and repulling them did not work for me.

**Comment by keenon** [comment]
Bump. Running Docker inside Vagrant and VirtualBox on OSX 10.9. Hangs on "Waiting for master".

**Comment by jancona** [comment]
I am seeing this issue on a physical machine running Ubuntu 13.10 and Docker 0.9.1. I did a docker rmi and re-pulled with no change. docker images reports:

```
amplab/dnsmasq-precise       latest              d9cdba2ae123        3 weeks ago         205.8 MB
amplab/spark-master          0.9.0               79d6b59ac67e        6 weeks ago         865.5 MB
```

I also tried it on a Mac using boot2docker with the same result.

**Comment by AndreSchumacher** [comment]
Sorry for the delay. I rebuilt the images from scratch now inside the VM on Mac OS. It should work now both inside the VM and natively. Thanks @flowfeeler for pointing out that the build itself works elsewhere.

So please everyone: repull once more. It should work now.

Edit1: I would be grateful for test reports. So far I only re-uploaded Spark 0.9. since I would like to make sure that this works.

**Comment by michaelpisula** [comment]
Works for me now, thanks for fixing :+1:

**Comment by jancona** [comment]
Working now, thanks!

**Comment by clausd** [comment]
Also working here - great!

**Comment by jancona** [comment]
I still have the same problem with the shark-0.8.0 master. Perhaps the other images need to be rebuilt?

**Comment by AndreSchumacher** [comment]
Thanks everyone for the test report. @jancona now that I know that Spark is working I will do the same for those images.

It would be interesting to know what the root cause of this problem was. I suspect it had something to do with the kernel version maybe. In any case I will switch to building images inside the "standard" VM.

**Comment by AndreSchumacher** [comment]
@jancona I rebuilt and pushed the shark images. They should work now. If not, please open a separate issue. I'm closing this one now.

**Comment by jancona** [comment]
The new Shark images worked for me. Thanks!
